### ISSUE TITLE
タブの線が選択時にきちんと消えるようにする

### ISSUE THREAD

**Issue by clio209** [clio209/noukaweb-pest-control-calender#57]
![農家web防除暦](https://user-images.githubusercontent.com/64455939/182754605-ba577483-9c32-451d-89f5-87955f8d833e.png)

**Comment by clio209** [comment]
```css
&:hover {
      background-color: white;
  }
&:focus-within {
background-color: #ffffff;
border-bottom: solid 2px #ffffff;
}
```
でも、選択した後、その状態を維持はできない・・・そうすればいいのか・・
